get validators info from proxy endpoint
ElrondNetwork/elrond-sdk-erdgo pull request #107
Opened 2022-12-08 10:28 UTC by ssd04

2022-12-13 12:27 UTC, schimih submitted a review, later dismissed

2022-12-13 12:27 UTC, schimih commented on headerCheck/headerCheck.go
> +// VerifyHeaderSignatureByHash verifies wether a header signature matches by providing
```suggestion
// VerifyHeaderSignatureByHash verifies whether a header signature matches by providing
```

2022-12-13 17:00 UTC, AdoAdoAdo requested changes

2022-12-13 21:54 UTC, ssd04 commented on examples/examplesHeaderCheck/main.go
> +	// set enable epochs config based on the environment
done

2022-12-14 08:34 UTC, AdoAdoAdo approved these changes

2022-12-14 09:19 UTC, merged